version: "3.8"
services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root 
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017" 
    volumes:
      - db:/data/db
  nodejs:
    image: node:20-alpine
    command: sh -c "yarn install && yarn start" 
    build: .
    restart: always
    env_file: ./.env
    ports:
      - "5000:3000"
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mongodb 
    environment:
      - DB_HOST=mongodb
      - DB_USER=dinhtuankiet
      - DB_PASSWORD=dinhtuankiet
      - DB_NAME=linkedin
      - DB_PORT=8017 
      - MONGO_URI=mongodb://mongodb:27017/myapp
    stdin_open: true
    tty: true
volumes:
  db: